# ============================================================
# 下载星露谷真实物品贴图（来自官方 Wiki）到本地 img/ 文件夹
# 需要网络；已下载过的文件会自动跳过，可重复运行
# 位置：本脚本在 scripts/ 子目录，项目根目录为其上一级
# ============================================================
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$ErrorActionPreference = "Continue"
$Root = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $Root

# 物品 id -> Wiki 文件名
$items = @{
  # ---------- 农作物 ----------
  "parsnip"     = "Parsnip.png"
  "potato"      = "Potato.png"
  "greenbean"   = "Green_Bean.png"
  "cauliflower" = "Cauliflower.png"
  "strawberry"  = "Strawberry.png"
  "kale"        = "Kale.png"
  "blueberry"   = "Blueberry.png"
  "melon"       = "Melon.png"
  "tomato"      = "Tomato.png"
  "hotpepper"   = "Hot_Pepper.png"
  "wheat"       = "Wheat.png"
  "corn"        = "Corn.png"
  "sunflower"   = "Sunflower.png"
  "pumpkin"     = "Pumpkin.png"
  "cranberry"   = "Cranberries.png"
  "eggplant"    = "Eggplant.png"
  "yam"         = "Yam.png"
  "amaranth"    = "Amaranth.png"
  "artichoke"   = "Artichoke.png"
  "tulip"         = "Tulip.png"
  "blue-jazz"     = "Blue_Jazz.png"
  "coffee-bean"   = "Coffee_Bean.png"
  "rhubarb"       = "Rhubarb.png"
  "hops"          = "Hops.png"
  "starfruit"     = "Starfruit.png"
  "red-cabbage"   = "Red_Cabbage.png"
  "poppy"         = "Poppy.png"
  "summer-squash" = "Summer_Squash.png"
  "grape-crop"    = "Grape.png"
  "beet"          = "Beet.png"
  "bok-choy"      = "Bok_Choy.png"
  "ancient-fruit" = "Ancient_Fruit.png"
  # ---------- 收集物 ----------
  "wild-horseradish" = "Wild_Horseradish.png"
  "daffodil"         = "Daffodil.png"
  "leek"             = "Leek.png"
  "dandelion"        = "Dandelion.png"
  "spring-onion"     = "Spring_Onion.png"
  "spice-berry"      = "Spice_Berry.png"
  "grape"            = "Grape.png"
  "sweet-pea"        = "Sweet_Pea.png"
  "fiddlehead-fern"  = "Fiddlehead_Fern.png"
  "common-mushroom"  = "Common_Mushroom.png"
  "wild-plum"        = "Wild_Plum.png"
  "hazelnut"         = "Hazelnut.png"
  "blackberry"       = "Blackberry.png"
  "chanterelle"      = "Chanterelle.png"
  "winter-root"      = "Winter_Root.png"
  "crystal-fruit"    = "Crystal_Fruit.png"
  "snow-yam"         = "Snow_Yam.png"
  "crocus"           = "Crocus.png"
  "holly"            = "Holly.png"
  "red-mushroom"     = "Red_Mushroom.png"
  "coral"            = "Coral.png"
  "sea-urchin"       = "Sea_Urchin.png"
  "rainbow-shell"    = "Rainbow_Shell.png"
  "nautilus-shell"   = "Nautilus_Shell.png"
  "coconut"          = "Coconut.png"
  "cactus-fruit"     = "Cactus_Fruit.png"
  # ---------- 收集物补全 ----------
  "cave-carrot"      = "Cave_Carrot.png"
  "purple-mushroom"  = "Purple_Mushroom.png"
  "truffle"          = "Truffle.png"
  "ginger"           = "Ginger.png"
  "seaweed"          = "Seaweed.png"
  "magma-cap"        = "Magma_Cap.png"
  "dinosaur-egg"     = "Dinosaur_Egg.png"
  # ---------- 钓鱼（山湖/河流） ----------
  "carp"             = "Carp.png"
  "largemouth"       = "Largemouth_Bass.png"
  "rainbow"          = "Rainbow_Trout.png"
  "sturgeon"         = "Sturgeon.png"
  "bullhead"         = "Bullhead.png"
  "chub"             = "Chub.png"
  "lingcod"          = "Lingcod.png"
  "legend"           = "Legend.png"
  "sunfish"          = "Sunfish.png"
  "smallmouth"       = "Smallmouth_Bass.png"
  "walleye"          = "Walleye.png"
  "perch"            = "Perch.png"
  "bream"            = "Bream.png"
  "shad"             = "Shad.png"
  "salmon"           = "Salmon.png"
  "tiger"            = "Tiger_Trout.png"
  "catfish"          = "Catfish.png"
  "pike"             = "Pike.png"
  "dorado"           = "Dorado.png"
  "angler"           = "Angler.png"
  "glacierfish"      = "Glacierfish.png"
  # ---------- 钓鱼（海洋/夜市） ----------
  "anchovy"          = "Anchovy.png"
  "sardine"          = "Sardine.png"
  "tuna"             = "Tuna.png"
  "red-snapper"      = "Red_Snapper.png"
  "squid"            = "Squid.png"
  "sea-cucumber"     = "Sea_Cucumber.png"
  "herring"          = "Herring.png"
  "eel"              = "Eel.png"
  "octopus"          = "Octopus.png"
  "pufferfish"       = "Pufferfish.png"
  "halibut"          = "Halibut.png"
  "red-mullet"       = "Red_Mullet.png"
  "tilapia"          = "Tilapia.png"
  "albacore"         = "Albacore.png"
  "flounder"         = "Flounder.png"
  "super-cucumber"   = "Super_Cucumber.png"
  "crimsonfish"      = "Crimsonfish.png"
  "midnight-squid"   = "Midnight_Squid.png"
  "spook-fish"       = "Spook_Fish.png"
  "blobfish"         = "Blobfish.png"
  # ---------- 钓鱼（蟹笼） ----------
  "lobster"          = "Lobster.png"
  "crab"             = "Crab.png"
  "clam"             = "Clam.png"
  "oyster"           = "Oyster.png"
  "mussel"           = "Mussel.png"
  "cockle"           = "Cockle.png"
  "shrimp"           = "Shrimp.png"
  "crayfish"         = "Crayfish.png"
  "snail"            = "Snail.png"
  "periwinkle"       = "Periwinkle.png"
  # ---------- 钓鱼（矿井/沙漠/其他/姜岛） ----------
  "stonefish"        = "Stonefish.png"
  "ghostfish"        = "Ghostfish.png"
  "ice-pip"          = "Ice_Pip.png"
  "lava-eel"         = "Lava_Eel.png"
  "sandfish"         = "Sandfish.png"
  "scorpion-carp"    = "Scorpion_Carp.png"
  "woodskip"         = "Woodskip.png"
  "mutant-carp"      = "Mutant_Carp.png"
  "void-salmon"      = "Void_Salmon.png"
  "stingray"         = "Stingray.png"
  "lionfish"         = "Lionfish.png"
  "blue-discus"      = "Blue_Discus.png"
  "midnight-carp"    = "Midnight_Carp.png"
  "son-of-crimsonfish" = "Son_of_Crimsonfish.png"
  "legend-2"         = "Legend_II.png"
  "glacierfish-jr"   = "Glacierfish_Jr..png"
  "ms-angler"        = "Ms._Angler.png"
  # ---------- NPC 头像（保存为 npc-<id>.png） ----------
  "npc-abigail"    = "Abigail.png"
  "npc-leah"       = "Leah.png"
  "npc-penny"      = "Penny.png"
  "npc-maru"       = "Maru.png"
  "npc-emily"      = "Emily.png"
  "npc-haley"      = "Haley.png"
  "npc-sam"        = "Sam.png"
  "npc-sebastian"  = "Sebastian.png"
  "npc-alex"       = "Alex.png"
  "npc-harvey"     = "Harvey.png"
  "npc-elliott"    = "Elliott.png"
  "npc-shane"      = "Shane.png"
  "npc-robin"      = "Robin.png"
  "npc-clint"      = "Clint.png"
  "npc-marnie"     = "Marnie.png"
  "npc-pierre"     = "Pierre.png"
  "npc-willy"      = "Willy.png"
  "npc-lewis"      = "Lewis.png"
  "npc-jodi"       = "Jodi.png"
  "npc-pam"        = "Pam.png"
  "npc-gus"        = "Gus.png"
  "npc-caroline"   = "Caroline.png"
  "npc-demetrius"  = "Demetrius.png"
  "npc-george"     = "George.png"
  "npc-evelyn"     = "Evelyn.png"
  "npc-vincent"    = "Vincent.png"
  "npc-jas"        = "Jas.png"
  "npc-kent"       = "Kent.png"
  "npc-sandy"      = "Sandy.png"
  "npc-rasmodius"  = "Wizard.png"
  "npc-marlon"     = "Marlon.png"
  "npc-gunther"    = "Gunther.png"
  "npc-krobus"     = "Krobus.png"
  # ---------- 特殊 NPC 补全 ----------
  "npc-gil"             = "Gil.png"
  "npc-governor"        = "Governor.png"
  "npc-old-mariner"     = "Old_Mariner.png"
  "npc-professor-snail" = "Professor_Snail.png"
  "npc-birdie"          = "Birdie.png"
  "npc-fizz"            = "Fizz_00.png"
  "npc-bouncer"         = "Bouncer.png"
  "npc-henchman"        = "Henchman_Portrait_1.png"
  # ---------- 采矿（矿石/矿物/宝石） ----------
  "copper"        = "Copper_Ore.png"
  "iron"          = "Iron_Ore.png"
  "gold-ore"      = "Gold_Ore.png"
  "iridium"       = "Iridium_Ore.png"
  "coal"          = "Coal.png"
  "quartz"        = "Quartz.png"
  "amethyst"      = "Amethyst.png"
  "topaz"         = "Topaz.png"
  "emerald"       = "Emerald.png"
  "ruby"          = "Ruby.png"
  "diamond"       = "Diamond.png"
  "prismatic"     = "Prismatic_Shard.png"
  # ---------- 战斗（怪物） ----------
  "green-slime"   = "Green_Slime.png"
  "blue-slime"    = "Blue_Slime.png"
  "rock-crab"     = "Rock_Crab.png"
  "cave-fly"      = "Cave_Fly.png"
  "bat"           = "Bat.png"
  "duggy"         = "Duggy.png"
  "skeleton"      = "Skeleton.png"
  "ghost"         = "Ghost.png"
  "shadow-brute"  = "Shadow_Brute.png"
  "purple-slime"  = "Purple_Slime.png"
  "serpent"       = "Serpent.png"
  "mummy"         = "Mummy.png"
  # ---------- 采矿补全（宝石/矿物） ----------
  "aquamarine"    = "Aquamarine.png"
  "jade"          = "Jade.png"
  "opal"          = "Opal.png"
  "fire-opal"     = "Fire_Opal.png"
  "earth-crystal" = "Earth_Crystal.png"
  "frozen-tear"   = "Frozen_Tear.png"
  "fire-quartz"   = "Fire_Quartz.png"
  "obsidian"      = "Obsidian.png"
  "clay"          = "Clay.png"
  "marble"        = "Marble.png"
  "granite"       = "Granite.png"
  "slate"         = "Slate.png"
  "sandstone"     = "Sandstone.png"
  "limestone"     = "Limestone.png"
  "basalt"        = "Basalt.png"
  "dolomite"      = "Dolomite.png"
  "thunder-egg"   = "Thunder_Egg.png"
  "tigers-eye"    = "Tigerseye.png"
  "star-shard"    = "Star_Shards.png"
  "petrified-slime" = "Petrified_Slime.png"
  # ---------- 采矿补全（晶球/金属锭/晶洞矿物/资源） ----------
  "frozen-geode"    = "Frozen_Geode.png"
  "magma-geode"     = "Magma_Geode.png"
  "omni-geode"      = "Omni_Geode.png"
  "copper-bar"      = "Copper_Bar.png"
  "iron-bar"        = "Iron_Bar.png"
  "gold-bar"        = "Gold_Bar.png"
  "iridium-bar"     = "Iridium_Bar.png"
  "radioactive-ore" = "Radioactive_Ore.png"
  "radioactive-bar" = "Radioactive_Bar.png"
  "wood"            = "Wood.png"
  "cinder-shard"    = "Cinder_Shard.png"
  "battery-pack"    = "Battery_Pack.png"
  "nekoite"         = "Nekoite.png"
  "helvite"         = "Helvite.png"
  "geminite"        = "Geminite.png"
  "lemon-stone"     = "Lemon_Stone.png"
  "neptunite"       = "Neptunite.png"
  "ocean-stone"     = "Ocean_Stone.png"
  "esperite"        = "Esperite.png"
  "fairy-stone"     = "Fairy_Stone.png"
  "jamborite"       = "Jamborite.png"
  "alamite"         = "Alamite.png"
  "lunarite"        = "Lunarite.png"
  "jagoite"         = "Jagoite.png"
  "aerinite"        = "Aerinite.png"
  "bixite"          = "Bixite.png"
  # ---------- 战斗补全（矿井/沙漠/姜岛） ----------
  "lava-crab"     = "Lava_Crab.png"
  "grub"          = "Grub.png"
  "dust-sprite"   = "Dust_Sprite.png"
  "frost-bat"     = "Frost_Bat.png"
  "lava-bat"      = "Lava_Bat.png"
  "shadow-shaman" = "Shadow_Shaman.png"
  "red-slime"     = "Red_Slime.png"
  "copper-slime"  = "Copper_Slime.png"
  "iron-slime"    = "Iron_Slime.png"
  "metal-head"    = "Metal_Head.png"
  "magma-sprite"  = "Magma_Sprite.png"
  "wilderness-golem" = "Wilderness_Golem.png"
  "mutant-grub"   = "Mutant_Grub.png"
  "mutant-fly"    = "Mutant_Fly.png"
  "tiger-slime"   = "Tiger_Slime.png"
  "iridium-bat"   = "Iridium_Bat.png"
  "iridium-crab"  = "Iridium_Crab.png"
  "magma-sparker" = "Magma_Sparker.png"
  # ---------- 战斗补全（危险矿井/骷髅洞穴/火山地牢） ----------
  "lava-lurk"             = "Lava_Lurk.png"
  "bug"                   = "Bug.png"
  "armored-bug"           = "Armored_Bug.png"
  "haunted-skull"         = "Haunted_Skull.png"
  "carbon-ghost"          = "Carbon_Ghost.png"
  "pepper-rex"            = "Pepper_Rex.png"
  "hot-head"              = "Hot_Head.png"
  "shadow-sniper"         = "Shadow_Sniper.png"
  "stick-bug"             = "Stick_Bug.png"
  "putrid-ghost"          = "Putrid_Ghost.png"
  "haunted-skull-dangerous" = "Haunted_Skull_Dangerous.png"
  "armored-bug-dangerous"   = "Armored_Bug_Dangerous.png"
  "bug-dangerous"           = "Bug_Dangerous.png"
  # ---------- 种子（第十四轮补） ----------
  "ancient-seeds" = "Ancient_Seeds.png"
  "cactus-seeds" = "Cactus_Seeds.png"
  "winter-seeds" = "Winter_Seeds.png"
  "pumpkin-seeds" = "Pumpkin_Seeds.png"
  "sunflower-seeds" = "Sunflower_Seeds.png"
  "hops-starter" = "Hops_Starter.png"
  "potato-seeds" = "Potato_Seeds.png"
  "spangle-seeds" = "Spangle_Seeds.png"
  "summer-seeds" = "Summer_Seeds.png"
  "garlic-seeds" = "Garlic_Seeds.png"
  "rhubarb-seeds" = "Rhubarb_Seeds.png"
  "bok-choy-seeds" = "Bok_Choy_Seeds.png"
  "wheat-seeds" = "Wheat_Seeds.png"
  "yam-seeds" = "Yam_Seeds.png"
  "spring-seeds" = "Spring_Seeds.png"
  "apricot-sapling" = "Apricot_Sapling.png"
  "starfruit-seeds" = "Starfruit_Seeds.png"
  "pine-cone" = "Pine_Cone.png"
  "maple-seed" = "Maple_Seed.png"
  "peach-sapling" = "Peach_Sapling.png"
  "mahogany-seed" = "Mahogany_Seed.png"
  "cherry-sapling" = "Cherry_Sapling.png"
  "orange-sapling" = "Orange_Sapling.png"
  "acorn" = "Acorn.png"
  "artichoke-seeds" = "Artichoke_Seeds.png"
  "mixed-seeds" = "Mixed_Seeds.png"
  "mixed-flower-seeds" = "Mixed_Flower_Seeds.png"
  "corn-seeds" = "Corn_Seeds.png"
  "fairy-seeds" = "Fairy_Seeds.png"
  "kale-seeds" = "Kale_Seeds.png"
  "melon-seeds" = "Melon_Seeds.png"
  "beet-seeds" = "Beet_Seeds.png"
  "pomegranate-sapling" = "Pomegranate_Sapling.png"
  "mystic-tree-seed" = "Mystic_Tree_Seed.png"
  "fall-seeds" = "Fall_Seeds.png"
  "rare-seed" = "Rare_Seed.png"
  "rice-shoot" = "Rice_Shoot.png"
  "red-cabbage-seeds" = "Red_Cabbage_Seeds.png"
  "fiber-seeds" = "Fiber_Seeds.png"
  "carrot-seeds" = "Carrot_Seeds.png"
  "taro-tuber" = "Taro_Tuber.png"
  "mango-sapling" = "Mango_Sapling.png"
  "cauliflower-seeds" = "Cauliflower_Seeds.png"
  "amaranth-seeds" = "Amaranth_Seeds.png"
  "apple-sapling" = "Apple_Sapling.png"
  "eggplant-seeds" = "Eggplant_Seeds.png"
  "tea-sapling" = "Tea_Sapling.png"
  "grass-starter" = "Grass_Starter.png"
  "strawberry-seeds" = "Strawberry_Seeds.png"
  "pineapple-seeds" = "Pineapple_Seeds.png"
  "radish-seeds" = "Radish_Seeds.png"
  "grape-starter" = "Grape_Starter.png"
  "jazz-seeds" = "Jazz_Seeds.png"
  "blue-grass-starter" = "Blue_Grass_Starter.png"
  "blueberry-seeds" = "Blueberry_Seeds.png"
  "cranberry-seeds" = "Cranberry_Seeds.png"
  "mushroom-tree-seed" = "Mushroom_Tree_Seed.png"
  "poppy-seeds" = "Poppy_Seeds.png"
  "tomato-seeds" = "Tomato_Seeds.png"
  "broccoli-seeds" = "Broccoli_Seeds.png"
  "pepper-seeds" = "Pepper_Seeds.png"
  "tulip-bulb" = "Tulip_Bulb.png"
  "summer-squash-seeds" = "Summer_Squash_Seeds.png"
  "mossy-seed" = "Mossy_Seed.png"
  "parsnip-seeds" = "Parsnip_Seeds.png"
  "powdermelon-seeds" = "Powdermelon_Seeds.png"
  "bean-starter" = "Bean_Starter.png"
  "banana-sapling" = "Banana_Sapling.png"
  "qi-bean" = "Qi_Bean.png"
  # ---------- 果树（第十六轮补；图标用**果实图** 48×48，树图 96×160 会造成非整数缩放） ----------
  "apricot" = "Apricot.png"
  "peach" = "Peach.png"
  "cherry" = "Cherry.png"
  "orange" = "Orange.png"
  "pomegranate" = "Pomegranate.png"
  "mango-tree" = "Mango.png"
  "apple" = "Apple.png"
  "banana" = "Banana.png"
  # ---------- 树木（第十八轮补；下载的是种子图，存成树自己的 id——树图 96×200 会造成非整数缩放） ----------
  "pine-tree" = "Pine_Cone.png"
  "maple-tree" = "Maple_Seed.png"
  "oak-tree" = "Acorn.png"
  "mahogany-tree" = "Mahogany_Seed.png"
  "mystic-tree" = "Mystic_Tree_Seed.png"
  "green-rain-tree" = "Mossy_Seed.png"
  "tea-tree" = "Tea_Sapling.png"
  "palm-tree" = "Coconut.png"
  # ---------- 动物（第二十一轮补；牛/羊/猪/鸵鸟等原图大于 48x48，
  #            下载后需按整数倍最近邻缩放，见 test/check.js 的图片覆盖断言） ----------
  "white-chicken" = "White_Chicken.png"
  "void-chicken" = "Void_Chicken.png"
  "golden-chicken" = "Golden_Chicken.png"
  "duck" = "Duck.png"
  "rabbit" = "Rabbit.png"
  "dinosaur" = "Dinosaur.png"
  "cow" = "White_Cow.png"
  "goat" = "Goat.png"
  "sheep" = "Sheep.png"
  "pig" = "Pig.png"
  "ostrich" = "Ostrich.png"
  # ---------- 动物制品（第二十二轮补；史莱姆球原图 66x116，下载后按整数倍缩放到 48x48 内） ----------
  "rabbit-s-foot" = "Rabbit's_Foot.png"
  "wool" = "Wool.png"
  "slime" = "Slime.png"
  "slime-ball" = "Slime_Ball.png"
  "large-milk" = "Large_Milk.png"
  "large-goat-milk" = "Large_Goat_Milk.png"
  "large-egg" = "Large_Egg.png"
  "milk" = "Milk.png"
  "goat-milk" = "Goat_Milk.png"
  "void-egg" = "Void_Egg.png"
  "egg" = "Egg.png"
  "golden-egg" = "Golden_Egg.png"
  "roe" = "Roe.png"
  "duck-feather" = "Duck_Feather.png"
  "duck-egg" = "Duck_Egg.png"
  "ostrich-egg" = "Ostrich_Egg.png"
  # ---------- 工具（第二十三轮补；加热器/孵化器/自动抚摸机/自动采集器原图 48x72~96，
  #            下载后按整数倍缩放到 48x48 内；垃圾桶首级无图，取铜级；淘盘取铜淘盘） ----------
  "axe" = "Axe.png"
  "pickaxe" = "Pickaxe.png"
  "watering-can" = "Watering_Can.png"
  "hoe" = "Hoe.png"
  "trash-can" = "Trash_Can_Copper.png"
  "pan" = "Copper_Pan.png"
  "scythe" = "Scythe.png"
  "golden-scythe" = "Golden_Scythe.png"
  "iridium-scythe" = "Iridium_Scythe.png"
  "shears" = "Shears.png"
  "milk-pail" = "Milk_Pail.png"
  "heater" = "Heater.png"
  "hay-hopper" = "Hay_Hopper.png"
  "incubator" = "Incubator.png"
  "auto-petter" = "Auto-Petter.png"
  "auto-grabber" = "Auto-Grabber.png"
  "bamboo-pole" = "Bamboo_Pole.png"
  "training-rod" = "Training_Rod.png"
  "fiberglass-rod" = "Fiberglass_Rod.png"
  "iridium-rod" = "Iridium_Rod.png"
  "advanced-iridium-rod" = "Advanced_Iridium_Rod.png"
  # ---------- 建筑（第二十四轮补；图源是**游戏截图**（铁匠铺 768x544、赌场 896x449），
  #            需要按整数倍缩放到 96x96 内，配 .item-icon.icon-lg 的大图标位） ----------
  "farmhouse" = "Farmhouse.png"
  "harvey-s-clinic" = "Harvey's_Clinic.png"
  "museum" = "Museum.png"
  "jojamart" = "JojaMart.png"
  "slime-hutch" = "Slime_Hutch.png"
  "ice-cream-stand" = "Ice_Cream_Stand.png"
  "joja-warehouse" = "Joja_Warehouse.png"
  "farm-obelisk" = "Farm_Obelisk.png"
  "witch-s-hut" = "Witch's_Hut.png"
  "shed" = "Shed.png"
  "earth-obelisk" = "Earth_Obelisk.png"
  "island-trader" = "Island_Trader.png"
  "island-obelisk" = "Island_Obelisk.png"
  "island-farmhouse" = "Island_Farmhouse.png"
  "giant-stump" = "Giant_Stump.png"
  "pet-bowl" = "Pet_Bowl.png"
  "trailer" = "Trailer.png"
  "the-stardrop-saloon" = "The_Stardrop_Saloon.png"
  "traveling-cart" = "Traveling_Cart.png"
  "abandoned-house" = "Abandoned_House.png"
  "adventurer-s-guild" = "Adventurer's_Guild.png"
  "carpenter-s-shop" = "Carpenter's_Shop.png"
  "tent" = "Tent.png"
  "island-field-office" = "Island_Field_Office.png"
  "well" = "Well.png"
  "1-river-road" = "1_River_Road.png"
  "1-willow-lane" = "1_Willow_Lane.png"
  "2-willow-lane" = "2_Willow_Lane.png"
  "water-obelisk" = "Water_Obelisk.png"
  "desert-trader" = "Desert_Trader.png"
  "desert-obelisk" = "Desert_Obelisk.png"
  "treehouse" = "Treehouse_Exterior.png"
  "pierre-s-general-store" = "Pierre's_General_Store.png"
  "greenhouse" = "Greenhouse.png"
  "marnie-s-ranch" = "Marnie's_Ranch.png"
  "wizard-s-tower" = "Wizard's_Tower.png"
  "spa" = "Spa.png"
  "barn" = "Barn.png"
  "dog-pen" = "Dog_Pen.png"
  "movie-theater" = "Movie_Theater.png"
  "oasis" = "Oasis.png"
  "silo" = "Silo.png"
  "mill" = "Mill.png"
  "leah-s-cottage" = "Leah's_Cottage.png"
  "junimo-hut" = "Junimo_Hut.png"
  "elliott-s-cabin" = "Elliott's_Cabin.png"
  "cabin" = "Cabin.png"
  "blacksmith" = "Blacksmith.png"
  "fish-shop" = "Fish_Shop.png"
  "casino" = "Casino.png"
  "coop" = "Coop.png"
  "stable" = "Horse Stable.png"
  "gold-clock" = "Gold_Clock.png"
  "mayor-s-manor" = "Mayor's_Manor.png"
  "fish-pond" = "Fish_Pond.png"
  "qi-s-walnut-room" = "Qi's_Walnut_Room.png"
  # ---------- 武器（第二十五轮补；全部是 48x48 精灵，无需缩放） ----------
  "templar-s-blade" = "Templar's_Blade.png"
  "claymore" = "Claymore.png"
  "carving-knife" = "Carving_Knife.png"
  "alex-s-bat" = "Alex's_Bat.png"
  "sam-s-old-guitar" = "Sam's_Old_Guitar.png"
  "holy-blade" = "Holy_Blade.png"
  "harvey-s-mallet" = "Harvey's_Mallet.png"
  "seb-s-lost-mace" = "Seb's_Lost_Mace.png"
  "slingshot" = "Slingshot.png"
  "infinity-blade" = "Infinity_Blade.png"
  "the-slammer" = "The_Slammer.png"
  "infinity-gavel" = "Infinity_Gavel.png"
  "infinity-dagger" = "Infinity_Dagger.png"
  "cutlass" = "Cutlass.png"
  "insect-head" = "Insect_Head.png"
  "meowmere" = "Meowmere.png"
  "neptune-s-glaive" = "Neptune's_Glaive.png"
  "wood-club" = "Wood_Club.png"
  "wood-mallet" = "Wood_Mallet.png"
  "wooden-blade" = "Wooden_Blade.png"
  "forest-sword" = "Forest_Sword.png"
  "crystal-dagger" = "Crystal_Dagger.png"
  "shadow-dagger" = "Shadow_Dagger.png"
  "broken-trident" = "Broken_Trident.png"
  "lava-katana" = "Lava_Katana.png"
  "rusty-sword" = "Rusty_Sword.png"
  "pirate-s-sword" = "Pirate's_Sword.png"
  "tempered-broadsword" = "Tempered_Broadsword.png"
  "wind-spire" = "Wind_Spire.png"
  "maru-s-wrench" = "Maru's_Wrench.png"
  "penny-s-fryer" = "Penny's_Fryer.png"
  "haley-s-iron" = "Haley's_Iron.png"
  "femur" = "Femur.png"
  "dwarf-hammer" = "Dwarf_Hammer.png"
  "dwarf-sword" = "Dwarf_Sword.png"
  "elf-blade" = "Elf_Blade.png"
  "dwarf-dagger" = "Dwarf_Dagger.png"
  "rapier" = "Rapier.png"
  "elliott-s-pencil" = "Elliott's_Pencil.png"
  "leah-s-whittler" = "Leah's_Whittler.png"
  "lead-rod" = "Lead_Rod.png"
  "galaxy-hammer" = "Galaxy_Hammer.png"
  "steel-smallsword" = "Steel_Smallsword.png"
  "iron-edge" = "Iron_Edge.png"
  "steel-falchion" = "Steel_Falchion.png"
  "iron-dirk" = "Iron_Dirk.png"
  "wicked-kris" = "Wicked_Kris.png"
  "iridium-needle" = "Iridium_Needle.png"
  "galaxy-slingshot" = "Galaxy_Slingshot.png"
  "galaxy-sword" = "Galaxy_Sword.png"
  "yeti-tooth" = "Yeti_Tooth.png"
  "kudgel" = "Kudgel.png"
  "silver-saber" = "Silver_Saber.png"
  "burglar-s-shank" = "Burglar's_Shank.png"
  "galaxy-dagger" = "Galaxy_Dagger.png"
  "abby-s-planchette" = "Abby's_Planchette.png"
  "obsidian-edge" = "Obsidian_Edge.png"
  "master-slingshot" = "Master_Slingshot.png"
  "dragontooth-club" = "Dragontooth_Club.png"
  "bone-sword" = "Bone_Sword.png"
  "dark-sword" = "Dark_Sword.png"
  "dragontooth-cutlass" = "Dragontooth_Cutlass.png"
  "dragontooth-shiv" = "Dragontooth_Shiv.png"
  "ossified-blade" = "Ossified_Blade.png"
  # ---------- 戒指（第二十六轮补；全部是 48x48 精灵，无需缩放） ----------
  "small-glow-ring" = "Small_Glow_Ring.png"
  "glow-ring" = "Glow_Ring.png"
  "slime-charmer-ring" = "Slime_Charmer_Ring.png"
  "vampire-ring" = "Vampire_Ring.png"
  "protection-ring" = "Protection_Ring.png"
  "soul-sapper-ring" = "Soul_Sapper_Ring.png"
  "phoenix-ring" = "Phoenix_Ring.png"
  "immunity-band" = "Immunity_Band.png"
  "small-magnet-ring" = "Small_Magnet_Ring.png"
  "magnet-ring" = "Magnet_Ring.png"
  "aquamarine-ring" = "Aquamarine_Ring.png"
  "burglar-s-ring" = "Burglar's_Ring.png"
  "jukebox-ring" = "Jukebox_Ring.png"
  "napalm-ring" = "Napalm_Ring.png"
  "lucky-ring" = "Lucky_Ring.png"
  "hot-java-ring" = "Hot_Java_Ring.png"
  "ruby-ring" = "Ruby_Ring.png"
  "emerald-ring" = "Emerald_Ring.png"
  "jade-ring" = "Jade_Ring.png"
  "topaz-ring" = "Topaz_Ring.png"
  "amethyst-ring" = "Amethyst_Ring.png"
  "savage-ring" = "Savage_Ring.png"
  "crabshell-ring" = "Crabshell_Ring.png"
  # ---------- 工匠制品（第三十轮补；树液采集器产物。上一轮入库时漏了贴图，
  #            详情/卡片上一直显示兜底 SVG。Wiki 原图即 48x48，1:1 无需缩放） ----------
  "pine-tar"    = "Pine_Tar.png"
  "maple-syrup" = "Maple_Syrup.png"
  "oak-resin"   = "Oak_Resin.png"
  "sap"         = "Sap.png"
}

$imgDir = Join-Path $Root "img"
New-Item -ItemType Directory -Force -Path $imgDir | Out-Null

# 分批查询（MediaWiki 的 titles 参数单次最多 50 个）
Write-Host "正在从星露谷 Wiki 获取图片地址（分批查询）..." -ForegroundColor Cyan
$byTitle = @{}
$entries = @($items.GetEnumerator())
for ($i = 0; $i -lt $entries.Count; $i += 50) {
    $end = [Math]::Min($i + 49, $entries.Count - 1)
    $batch = $entries[$i..$end]
    $titles = ($batch | ForEach-Object { "File:" + $_.Value }) -join "|"
    $api = "https://stardewvalleywiki.com/mediawiki/api.php?action=query&titles=$titles&prop=imageinfo&iiprop=url&format=json&formatversion=2"
    try {
        $json = Invoke-RestMethod -Uri $api -TimeoutSec 60 -Headers @{ "User-Agent" = "StardewGuideFanSite/1.0" }
        if ($json.query.pages) {
            foreach ($page in $json.query.pages) {
                # MediaWiki 会把标题中的下划线规范化为空格，统一转为下划线再匹配
                if ($page.imageinfo -and $page.imageinfo.Count -gt 0) { $byTitle[($page.title -replace " ", "_")] = $page.imageinfo[0].url }
            }
        }
    } catch {
        Write-Host "✗ 第 $($i / 50 + 1) 批查询失败：$($_.Exception.Message)" -ForegroundColor Red
    }
}
if ($byTitle.Count -eq 0) {
    Write-Host "✗ 未能获取任何图片地址（Wiki 请求全部失败）" -ForegroundColor Red
    Write-Host "（站点会使用备用图标，不影响上线）" -ForegroundColor Yellow
    exit 1
}

# 英文名页面兜底（查条目页配图）。
# 仅当某条目的 Wiki 文件名与「条目名.png」惯例不符、且 pageimages 也无法直接定位时才需要在此登记，
# 键为 data.js 的 id，值为 Wiki 上的英文条目名（依 R13：不要手工猜文件名）。
# 2026-10-07 清理：原表 9 条全部失效——zombie/gypsum/salt/stone-bat 属已删除的编造条目（#14），
#   cave-grub 已正名为 grub，iridium-slime 经查证实为编造条目（#34），
#   gold-slime 在 Wiki 上无条目页也无图片（走 SVG 兜底），
#   star-shard/tigers-eye 的英文页名本就写错（正确为 Star Shards / Tigerseye），且已在 $items 中登记。
$pageNames = @{}

function Get-FileUrl([string]$file) {
    # 兜底1：单文件查询 + 跟随重定向
    $api = "https://stardewvalleywiki.com/mediawiki/api.php?action=query&titles=File:" + [uri]::EscapeDataString($file) + "&prop=imageinfo&iiprop=url&format=json&formatversion=2&redirects=1"
    try {
        $j = Invoke-RestMethod -Uri $api -TimeoutSec 30 -Headers @{ "User-Agent" = "StardewGuideFanSite/1.0" }
        if ($j.query.pages -and $j.query.pages.Count -gt 0 -and $j.query.pages[0].imageinfo) {
            return $j.query.pages[0].imageinfo[0].url
        }
    } catch { }
    return $null
}

function Get-PageImage([string]$page) {
    # 兜底2：查询条目页的主图（pageimages），对物品/怪物最可靠
    $api = "https://stardewvalleywiki.com/mediawiki/api.php?action=query&titles=" + [uri]::EscapeDataString($page) + "&prop=pageimages&piprop=original&format=json&formatversion=2"
    try {
        $j = Invoke-RestMethod -Uri $api -TimeoutSec 30 -Headers @{ "User-Agent" = "StardewGuideFanSite/1.0" }
        if ($j.query.pages -and $j.query.pages.Count -gt 0 -and $j.query.pages[0].original) {
            return $j.query.pages[0].original.source
        }
    } catch { }
    return $null
}

function Find-WikiFile([string]$id) {
    # 兜底3：按英文名在文件命名空间搜索（修复 File: 前缀匹配）
    $term = $pageNames[$id]
    if (-not $term) { return $null }
    $searchApi = "https://stardewvalleywiki.com/mediawiki/api.php?action=query&list=search&srnamespace=6&srsearch=" + [uri]::EscapeDataString($term) + "&srlimit=8&format=json&formatversion=2"
    try {
        $sj = Invoke-RestMethod -Uri $searchApi -TimeoutSec 30 -Headers @{ "User-Agent" = "StardewGuideFanSite/1.0" }
        if (-not $sj.query.search -or $sj.query.search.Count -eq 0) { return $null }
        # 优先：完全同名 .png → 名称开头 .png → 任意 .png → 第一个结果
        $hit = $null
        foreach ($r in $sj.query.search) { $t = $r.title -replace "^File:", ""; if ($t -eq ($term + ".png")) { $hit = $t; break } }
        if (-not $hit) { foreach ($r in $sj.query.search) { $t = $r.title -replace "^File:", ""; if ($t -like ($term + "*") -and $t -like "*.png") { $hit = $t; break } } }
        if (-not $hit) { foreach ($r in $sj.query.search) { $t = $r.title -replace "^File:", ""; if ($t -like "*.png") { $hit = $t; break } } }
        if (-not $hit -and $sj.query.search.Count -gt 0) { $hit = $sj.query.search[0].title -replace "^File:", "" }
        if (-not $hit) { return $null }
        return Get-FileUrl $hit
    } catch { }
    return $null
}

$ok = 0; $skip = 0; $fail = @()
foreach ($e in $items.GetEnumerator()) {
    $out = Join-Path $imgDir ($e.Key + ".png")
    if ((Test-Path $out) -and ((Get-Item $out).Length -gt 0)) { $skip++; continue }
    $url = $byTitle["File:" + $e.Value]
    if (-not $url) { $url = Get-FileUrl $e.Value }
    if (-not $url -and $pageNames[$e.Key]) { $url = Get-PageImage $pageNames[$e.Key] }
    if (-not $url) { $url = Find-WikiFile $e.Key }
    if (-not $url) { $fail += $e.Key; continue }
    try {
        Invoke-WebRequest -Uri $url -OutFile $out -UseBasicParsing -TimeoutSec 30
        $ok++
    } catch { $fail += $e.Key }
}

Write-Host ""
Write-Host ("完成：新下载 {0} 个，已存在跳过 {1} 个，失败 {2} 个" -f $ok, $skip, $fail.Count) -ForegroundColor Green
if ($fail.Count) {
    Write-Host ("失败项：" + ($fail -join ", ")) -ForegroundColor Yellow
    Write-Host "失败项可稍后重跑本脚本补下；页面会先用备用图标显示" -ForegroundColor Yellow
}
Write-Host ""
